Od zadania 1 do zadania 3
JohnyRLk/protractor-tutorial pull request #1
Opened 2021-07-06 06:40 UTC by JohnyRLk

2021-07-06 07:15 UTC, MichalFidor requested changes

2021-07-06 07:15 UTC, MichalFidor commented on excercises/2-locators/locators-element-all.spec.ts
>  		expect(await menuItems.get(0).getText()).toEqual(menuText[0]);
Why you checking here only one menuItem instead of whole list? Expect is not equal to the title of this it.

2021-07-06 07:15 UTC, MichalFidor commented on excercises/2-locators/locators-element-all.spec.ts
> +			autor =>  autor.name === 'Author Name')
Where is expect?

2021-07-06 07:15 UTC, MichalFidor commented on excercises/2-locators/locators-element.spec.ts
> +		let headlineWithXpath = element(by.xpath('//*[@id="myCarousel"]/div/div[1]/div/div/div[1]/div/h1')).getText();
Change this nasty xpath :)

2021-07-06 07:15 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
> +      }
What's this?! 😳😵 Where is expect?!

2021-07-06 07:15 UTC, MichalFidor commented on excercises/3-synchronization/home.spec.ts
> +		expect(browser.driver.wait(EC.invisibilityOf(gdrp)));
Expect what exactly? It's not a full assertion

2021-07-06 07:15 UTC, MichalFidor commented on excercises/3-synchronization/home.spec.ts
> +		//const activeCarouselHeader = element(by.xpath('//*[@id="myCarousel"]/div/div[2]/div/div/div[1]/div/h1'));
remove comments

2021-07-06 07:15 UTC, MichalFidor commented on excercises/3-synchronization/home.spec.ts
> +		checkDropdown.get(2).click();
You missing await here. And again, stop using idx.

2021-07-08 08:06 UTC, MichalFidor requested changes

2021-07-08 08:06 UTC, MichalFidor commented on excercises/2-locators/locators-element-all.spec.ts
> +
Why you change this it to something... totally strange? You only needs to add expect and check if you are on proper page. You are checking the 'Author name' which is okay but

1. Why you creating the onlynames function ? What is a purpose for this?
2. From 31 ro 36 line - do you know what exactly is happening in here?
3. Do you know what exactly method `filter` do?

This test is not working as you think. Did you check it in negative way?

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/contact.spec.ts
> +		const findkSuccessInformation = element(by.xpath("//h4[contains(text(), 'Your message has been sent.')]"));
typo

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
> +    }*/
remove comments

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
> +    expect(async function() {presentElement}).toThrowError(err());
You need to check if element is NOT present. Method err() throwing 'Element is present' . This test is totally missleading

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
> +    }*/
remove comments

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
> +    }*/
remove comments

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
> +  xit('should be usable in WebDriver functions', async function () {
Turn on its

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
>    });
where is expect?

2021-07-08 08:06 UTC, MichalFidor commented on excercises/3-synchronization/handling-errors.spec.ts
>    });
where is expect?

2021-07-08 08:06 UTC, MichalFidor commented on excercises/4-pop/pages/contact.ts
> +    const success = "Your message has been sent.";
The same thing as it was in jak-to-zrobic-w-js...

2021-07-08 08:06 UTC, MichalFidor commented on excercises/4-pop/pages/contact.ts
> +    await browser.wait(ec.textToBePresentInElement(getSuccess, success), 6000);
remove this success and change it to presence of element

2021-07-08 08:26 UTC, rafalszmit commented on excercises/1-configuration/home.spec.ts
> +import { browser, element, by } from 'protractor'
To keep code clean, remember to remove imports that you don't use. Here you don't use 'element' and 'by'.

2021-07-08 08:26 UTC, rafalszmit commented on excercises/2-locators/locators-element-all.spec.ts
> +import { getLeadingCommentRanges } from 'typescript';
you are not using that import

2021-07-08 08:26 UTC, rafalszmit commented on excercises/2-locators/locators-element-all.spec.ts
> +	it('should route to "Blog" pages after selecting link', async function () {
To be fair I don't even know what is the goal of this test.
I would even accept onlynames function on its own and then using it in filter but:
1. The function is checking something so 'onlynames' may not be best name. Function names should be camel case so 'onlyNames', I would name it 'compareName' or something.
2. You are comparing Author Name with Author Name so the result of filter function makes no difference to the array.
3. The mechanism on its own is ok for me, and as I don't know what that test should do

2021-07-08 08:32 UTC, rafalszmit commented on excercises/3-synchronization/home.spec.ts
> +		browser.sleep(10000);
why do we sleep 10s here?

2021-07-08 08:32 UTC, rafalszmit commented on excercises/3-synchronization/handling-errors.spec.ts
>    it('should not fail if element is not present', async function () {
also I understand that the test should not fail if browser will not find the element. I ran this test and it is failing.

2021-07-08 12:48 UTC, rafalszmit commented on excercises/4-pop/contact.spec.ts
> +		expect(getSuccess.isPresent()).toBe(true);
I think the previous way was actually better. That way you not only check if the success alert is displayed but also if it has expected text.

2021-07-08 13:56 UTC, merged